### ISSUE TITLE
Create CLI binary

### ISSUE THREAD

**Issue by levibostian** [levibostian/Purslane#2]
From the bash script prototype, it's time to create the CLI. 

This will take some time because it's my first Go lang program. We have to learn about the basics of the lang, tooling, testing. 

## Assumptions
- no volumes at this time. 
- no customization of provider (do vs linode)
- no customization of droplet. Just create the smallest one. 

# tasks
- [x] create a volume for DO account
- [x] create server for DO account
- [x] login to private docker repo on new server
- [x] docker image pull on new server. catch errors, if any. 
- [x] docker run image on new server. 
  - [x] allow through config being able to append args to docker run command. 
- [x] cleanup resources after docker login or error encountered
- [x] simple README documentation
  - [x] create example config file. Specifies required vs optional with default values. 
  - [x] Make note software is not unit tested. No warranty as this software may charge your credit card more then you wish.
